<?php

if ( function_exists( 'lazyblocks' ) ) :

lazyblocks()->add_block( array(
    'id' => 1805,
    'title' => 'Gigi',
    'icon' => '<svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24"><path d="M21 18v1c0 1.1-.9 2-2 2H5c-1.11 0-2-.9-2-2V5c0-1.1.89-2 2-2h14c1.1 0 2 .9 2 2v1h-9c-1.11 0-2 .9-2 2v8c0 1.1.89 2 2 2h9zm-9-2h10V8H12v8zm4-2.5c-.83 0-1.5-.67-1.5-1.5s.67-1.5 1.5-1.5 1.5.67 1.5 1.5-.67 1.5-1.5 1.5z" /></svg>',
    'keywords' => array(
    ),
    'slug' => 'lazyblock/ld-gigisorel',
    'description' => '',
    'category' => 'common',
    'category_label' => 'common',
    'supports' => array(
        'customClassName' => true,
        'anchor' => false,
        'align' => array(
            0 => 'wide',
            1 => 'full',
        ),
        'html' => false,
        'multiple' => true,
        'inserter' => true,
    ),
    'ghostkit' => array(
        'supports' => array(
            'spacings' => false,
            'display' => false,
            'scrollReveal' => false,
        ),
    ),
    'controls' => array(
        'control_c5bbb74b16' => array(
            'type' => 'text',
            'name' => 'bllll',
            'default' => 'werwerwerwe',
            'label' => 'Bllll',
            'help' => '',
            'child_of' => '',
            'placement' => 'inspector',
            'width' => '100',
            'hide_if_not_selected' => 'false',
            'save_in_meta' => 'false',
            'save_in_meta_name' => '',
            'required' => 'false',
            'placeholder' => '',
            'characters_limit' => '',
        ),
        'control_febbba4fc2' => array(
            'type' => 'color',
            'name' => 'testcolor',
            'default' => '',
            'label' => 'TestColor',
            'help' => '',
            'child_of' => '',
            'placement' => 'inspector',
            'width' => '100',
            'hide_if_not_selected' => 'false',
            'save_in_meta' => 'false',
            'save_in_meta_name' => '',
            'required' => 'false',
            'placeholder' => '',
            'characters_limit' => '',
        ),
        'control_440b354898' => array(
            'type' => 'toggle',
            'name' => 'uiti',
            'default' => '',
            'label' => 'uiti',
            'help' => '',
            'child_of' => '',
            'placement' => 'inspector',
            'width' => '100',
            'hide_if_not_selected' => 'false',
            'save_in_meta' => 'false',
            'save_in_meta_name' => '',
            'required' => 'false',
            'placeholder' => '',
            'characters_limit' => '',
        ),
        'control_40a9f542d0' => array(
            'type' => 'inner_blocks',
            'name' => 'utututyutyuty',
            'default' => '',
            'label' => 'utututyutyuty',
            'help' => '',
            'child_of' => '',
            'placement' => 'both',
            'width' => '100',
            'hide_if_not_selected' => 'false',
            'save_in_meta' => 'false',
            'save_in_meta_name' => '',
            'required' => 'false',
            'placeholder' => '',
            'characters_limit' => '',
        ),
        'control_c6d9954530' => array(
            'type' => 'range',
            'name' => 'rwefdgdfc',
            'default' => '',
            'label' => 'rwefdgdfc',
            'help' => '',
            'child_of' => '',
            'placement' => 'inspector',
            'width' => '100',
            'hide_if_not_selected' => 'false',
            'save_in_meta' => 'false',
            'save_in_meta_name' => '',
            'required' => 'false',
            'placeholder' => '',
            'characters_limit' => '',
        ),
    ),
    'code' => array(
        'editor_html' => '',
        'editor_callback' => '',
        'editor_css' => '',
        'frontend_html' => '<h1>
    {{bllll}}
</h1>
    {{{utututyutyuty}}}
',
        'frontend_callback' => '',
        'frontend_css' => '',
        'show_preview' => 'always',
        'single_output' => true,
        'use_php' => false,
    ),
    'condition' => array(
    ),
) );

endif;